### ISSUE TITLE
Sync Website Commits to Google Group

### ISSUE THREAD

**Issue by lewismc** [aria-p/aria-p.github.io#1]
All commits should be shadowed to the Google Group using [Github Hooks](https://help.github.com/articles/receiving-email-notifications-for-pushes-to-a-repository/)

**Comment by andychase** [comment]
Sounds good, only issue here I believe is that the ARIA-P Google Group is set to restrict on who can post to the list so I'm not sure the github emails could go through.

**Comment by andychase** [comment]
Figured it out. I just need to enable this option:

> `send_from_author` uses the commit author email address in the From address of the email.

Added.

**Comment by lewismc** [comment]
Nice. This addressed at Tickets for both website and project code?

On Tuesday, October 20, 2015, Andy Chase <notifications@github.com> wrote:

> Figured it out. I just need to enable this option:
>
> send_from_author uses the commit author email address in the From address
> of the email.
>
> Added.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aria-p/aria-p.github.io/issues/1#issuecomment-149792673>
> .
>


-- 
*Lewis*

**Comment by andychase** [comment]
Commits, yeah. I went ahead and added it for the project as well.
